name: Feature Request
description: Suggest a new feature or improvement for Rainmeter Editor.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide the details below.
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see.
      placeholder: The feature should allow users to...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Use Case
      description: Explain how this feature will be useful.
      placeholder: This feature will help users by...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Mention any alternative solutions you’ve considered.
      placeholder: Other approaches could be...
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or ideas related to the feature.
